---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Discover compute VMs on hypervisor
  hosts: hypervisor
  remote_user: zuul
  become: true
  gather_facts: false
  tasks:
    - name: List all running compute VMs
      ansible.builtin.shell: |
        virsh list --name | grep compute | sort
      register: compute_vms
      changed_when: false

    - name: Fetch UUID for each compute VM
      ansible.builtin.shell: |
        virsh dumpxml {{ item }} | grep uuid | head -1 | cut -d '>' -f 2 | cut -d '<' -f 1
      register: compute_uuids
      loop: "{{ compute_vms.stdout_lines }}"
      changed_when: false

    - name: Build fencing entries
      ansible.builtin.set_fact:
        compute_fencing_entries: >-
          {{ compute_fencing_entries | default([]) + [{
            'name': item.item | regex_replace('^cifmw-', ''),
            'agent': (idx == 1) | ternary('ipmi', 'redfish'),
            'ipaddr': '192.168.111.9',
            'ipport': (idx == 1) | ternary('6231', (8000 + idx) | string),
            'login': 'admin',
            'passwd': 'password',
            'uuid': item.stdout
          }] }}
      loop: "{{ compute_uuids.results }}"
      loop_control:
        index_var: idx

- name: Deploy Instance HA
  hosts: controller-0
  tasks:
    - name: Copy fencing-secret.yaml
      ansible.builtin.template:
        src: templates/fencing-secret.yaml.j2
        dest: /home/zuul/fencing-secret.yaml
      vars:
        compute_fencing_entries: "{{ hostvars['hypervisor']['compute_fencing_entries'] }}"

    - name: Copy iha-config.yaml
      ansible.builtin.template:
        src: templates/iha-cm.yaml.j2
        dest: /home/zuul/iha-cm.yaml

    - name: Copy iha.yaml
      ansible.builtin.template:
        src: templates/iha.yaml.j2
        dest: /home/zuul/iha.yaml

    - name: Deploy OCP resources
      ansible.builtin.shell: |
        oc project openstack; oc apply -f ~/fencing-secret.yaml
        oc project openstack; oc apply -f ~/iha-cm.yaml
        oc project openstack; oc apply -f ~/iha.yaml
      changed_when: false

    - name: Wait until InstanceHA pod is ready
      ansible.builtin.shell: |
        oc wait deployment/instanceha-0 -n openstack --for condition=Available --timeout=300s
      changed_when: false

    - name: Install prereq
      ansible.builtin.shell: |
        ansible-galaxy collection install openstack.cloud
        ansible-galaxy collection install community.libvirt
      changed_when: false
